# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';
in
linkFarm name [
  {
    name = "httpz-0.0.0-PNVzrDC4BwANG-9UeHJ5udYPc19jZpm6LbkAtlAElOBk.tar.gz";
    path = fetchZig {
      name = "httpz";
      url = "git+https://github.com/karlseguin/http.zig?ref=master#b0c3479b58f999f014862c35922eea1a56e5677a";
      hash = "sha256-p1oBir/1XC0sxv3DUPNY58GTpoVbbC5WnhRC5t/dJgc=";
    };
  }
  {
    name = "metrics-0.0.0-W7G4eIegAQD4XxA9Co7Atbw59u_2zvxYf406AZuoAHPM.tar.gz";
    path = fetchZig {
      name = "metrics";
      url = "https://github.com/karlseguin/metrics.zig/archive/6de29b83a750a06c438d268543e0e3c3c1b309da.tar.gz";
      hash = "sha256-2RJNeYM7KchngJGiedE7l9XVJTPNGG+eKpqTT53zlWg=";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdUU6BAAPe0iZ_JHMVAXaBlz327xZRBrRY06-Vw5h.tar.gz";
    path = fetchZig {
      name = "websocket";
      url = "https://github.com/karlseguin/websocket.zig/archive/3be6210f53297fb4b458d88562047ff4d69629a3.tar.gz";
      hash = "sha256-xnz9Mu/Fbmt5dFmEw3uPYbffZD8GjbvpKdH8GL56IkU=";
    };
  }
]
